name: Retrieve Secret from Azure Key Vault

on:
  push:
    branches:
      - main

jobs:
  get-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Retrieve and Echo Secret from Azure Key Vault
      run: |
        SECRET=$(az keyvault secret show --name hello --vault-name <Your-Key-Vault-Name> --query value -o tsv)
        echo "The secret value of hello is $SECRET"
